default_stages: [commit, push]
fail_fast: true
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: detect-private-key
    -   id: trailing-whitespace
    -   id: check-merge-conflict
    -   id: requirements-txt-fixer
    -   id: detect-aws-credentials
-   repo: https://gitlab.com/pycqa/flake8
    rev: '20906d43'
    hooks:
    -   id: flake8
        exclude: (tests|script)
-   repo: https://github.com/ambv/black
    rev: stable
    hooks:
    -   id: black
        language_version: python3.8
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: '6d1dbad'
    hooks:
    -   id: mypy
        exclude: ^doc/
-   repo: https://github.com/awslabs/cfn-python-lint
    rev: v0.15.0
    hooks:
    -   id: cfn-python-lint
        files: cfn/.*\.(yaml|yml)$
-   repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v1.0.0
    hooks:
    -    id: commitlint
         stages: [commit-msg]
# -   repo: local
#     hooks:
#     -   id: semantic-release
#         name: Semantic Release
#         entry: ./script/chkver.sh
#         language: script
