
name: Release
on:
  push:
    branches:
      - master

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: "13.x"
      - run: |
          npm install -g semantic-release           \
          "@semantic-release/changelog"             \
          "@semantic-release/commit-analyzer"       \
          "@semantic-release/git"                   \
          "@semantic-release/release-notes-generator"
          npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.SEMANTIC_RELEASE }}